### PR TITLE
Extruder v2

### LINKED ISSUE #98: E.PUE Fault on On Inverter after idling
The Inverter sets the E.PUE Fault after a time with default El6021 settings except baudrate and encoding

### LINKED ISSUE #99: Add a Translation Layer for Modbusrequest
When sending API Requests we dont want to send the raw Modbusrequest.
Instead we want to send something like ChangeFrequencyRequest{frequency:60.00}

### LINKED ISSUE #100: Add a Frequency Converter
The Frequency Converter should either normalise values to be between 0 and 1 or it checks that the values are in the specified range

### LINKED ISSUE #101: Add minimal Extruder backend/frontend
Create all Files needed for a minimal machine.
Just so we can select it in the frontend without any errors

### LINKED ISSUE #140: add/integrate EL1002

### LINKED ISSUE #141: add/integrate EL6021

### LINKED ISSUE #142: add/integrate EL2004

### LINKED ISSUE #143: add/integrate EL3021

### LINKED ISSUE #144: add/integrate EL3204

### LINKED ISSUE #148: add high level logic for standby/extrude/heat

### LINKED ISSUE #158: `El6021` not detected due to missing revision
Server panicks because EL6021 had an unexpected revision of 0x140000. It needs to be handled

### LINKED ISSUE #161: `El3204` not detected because of missing revision
The missing revision is: 0x150000

### LINKED ISSUE #176: Add Error Messages for Disconnected Temperature Sensor
In The Frontend we should show an error or Error Message showing that the temperature sensor is not connected correctly. When Sensors arent connected the Temp readout is 850 C° which is obviously wrong. We just need to check for overvoltage or undervoltage

### LINKED ISSUE #193: Use a `HashMap` instead of `VecDequeue` for modbus-requests
Mitsubishi-inverter should use a hashmap or similiar to avoid memory leakage if we send requests too fast. The idea is to overwrite certain requests instead of always adding a new object to the queue

### LINKED ISSUE #194: Reposition the elements in frontend
Temperature should positioned above the target temperature,
Measurements should be removed,
In general everything except buttons should be stacked horizontally

### PR DESCRIPTION
**Pull request by kraemr**
fix #98
fix #99 
fix #100
fix #101
fix #140 
fix #141 
fix #142 
fix #143 
fix #144 
fix #148 
fix #161 
fix #158
fix #176

### CODE REVIEW

File: control-core/src/actors/digital_output_blinker.rs [hunk 1]
```diff
@@ -7,6 +7,8 @@ use std::{
 };
 
 /// Set a digital output high and low with a given interval
+#[derive(Debug)]
+
```
Comment (1cedsoda) [inline control-core/src/actors/digital_output_blinker.rs]: remove empty line

File: control-core/src/actors/mitsubishi_inverter_rs485/init.rs [hunk 2]
```diff
@@ -0,0 +1 @@
+// In this file create all Requests that are needed to int the inverter
```
Comment (1cedsoda) [inline control-core/src/actors/mitsubishi_inverter_rs485/init.rs]: remove useless line

File: control-core/src/actors/mitsubishi_inverter_rs485/mod.rs [hunk 3]
```diff
@@ -164,20 +253,55 @@ pub enum MitsubishiControlRequests {
...
-    pub request_queue: VecDeque<ModbusRequest>,
+    pub request_queue: VecDeque<MitsubishiModbusRequest>,
     pub response_queue: VecDeque<ModbusResponse>,
+
+    pub forward_rotation: bool,
+    pub next_response_type: ResponseType,
+
+    pub current_freq: f32,
+    pub current_rpm: f32,
 }
```
Comment (1cedsoda) [inline control-core/src/actors/mitsubishi_inverter_rs485/mod.rs]: Please clean this up into different sections like
- stuff for communication
- state like frequency, rpm rotation

File: control-core/src/actors/mitsubishi_inverter_rs485/mod.rs [hunk 4]
```diff
@@ -164,20 +253,55 @@ pub enum MitsubishiControlRequests {
...
 
-    pub request_queue: VecDeque<ModbusRequest>,
+    pub request_queue: VecDeque<MitsubishiModbusRequest>,
     pub response_queue: VecDeque<ModbusResponse>,
+
+    pub forward_rotation: bool,
+    pub next_response_type: ResponseType,
+
+    pub current_freq: f32,
+    pub current_rpm: f32,
```
Comment (1cedsoda) [inline control-core/src/actors/mitsubishi_inverter_rs485/mod.rs]: remove everythong related to RPM

Comment (1cedsoda) [inline control-core/src/actors/mitsubishi_inverter_rs485/mod.rs]: use `uom` quantity for frequency

File: control-core/src/actors/mitsubishi_inverter_rs485/mod.rs [hunk 5]
```diff
@@ -219,20 +350,25 @@ impl MitsubishiInverterRS485Actor {
                 Some(res) => res,
                 None => {
                     log::error!("ERROR: No Modbus Response");
```
Comment (1cedsoda) [inline control-core/src/actors/mitsubishi_inverter_rs485/mod.rs]: I don't think this error should be logged

File: control-core/src/actors/mitsubishi_inverter_rs485/mod.rs [hunk 6]
```diff
@@ -208,7 +337,9 @@ impl MitsubishiInverterRS485Actor {
     }
 
     /// This is used internally to read the receive buffer of the el6021
-    fn read_modbus_response(&mut self) -> Pin<Box<dyn Future<Output = ()> + Send + '_>> {
+    fn read_modbus_response(
+        &mut self,
+    ) -> Pin<Box<dyn Future<Output = Result<ModbusResponse, anyhow::Error>> + Send + '_>> {
         Box::pin(async move {
             if !(self.serial_interface.has_message)().await {
                 //   return;
```
Comment (1cedsoda) [inline control-core/src/actors/mitsubishi_inverter_rs485/mod.rs:347]: whats this???

File: control-core/src/actors/temperature_input_getter.rs [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+
+impl TemperatureInputGetter {
+    pub fn new(input: TemperatureInput) -> Self {
+        Self {
+            input,
+            temperature: 0.0,
+            wiring_error: false,
+        }
+    }
+}
```
Comment (1cedsoda) [inline control-core/src/actors/temperature_input_getter.rs]: Here is a getter function appropriate instead of member access because this interface should just be used as read only even if it's owned

File: control-core/src/converters/motor_converter.rs [hunk 8]
```diff
@@ -0,0 +1,9 @@
+pub struct MotorConverter {}
+impl MotorConverter {
+    pub fn rpm_to_hz(rpm: f32) -> f32 {
+        rpm / 60.0
+    }
+    pub fn hz_to_rpm(hz: f32) -> f32 {
+        hz * 60.0
+    }
+}
```
Comment (1cedsoda) [inline control-core/src/converters/motor_converter.rs]: use `uom` like `AngularVelocity`

File: control-core/src/modbus/mod.rs [hunk 9]
```diff
@@ -37,24 +37,6 @@ pub struct ModbusResponse {
...
-
-    fn get_exception_code(self) -> u8 {
-        if self.data.len() > 3 {
-            let exception = self.data[2];
-            return exception;
-        }
-        return 0;
-    }
-}
-
```
Comment (1cedsoda) [inline control-core/src/modbus/mod.rs:57]: Please check with @Anatomik5 if this removal is ok

File: electron/src/machines/extruder/HeatingZone.tsx [hunk 10]
```diff
@@ -2,47 +2,67 @@ import { ControlCard } from "@/control/ControlCard";
 import { EditValue } from "@/control/EditValue";
 import { Label } from "@/control/Label";
 import { roundToDecimals } from "@/lib/decimal";
+import { Flame } from "lucide-react"; // Or any other icon library
```
Comment (1cedsoda) [inline electron/src/machines/extruder/HeatingZone.tsx]: Don't use `lucide-react` direclty use our Icon wrapper and access this icon via `lu:Flame`

File: electron/src/machines/extruder/extruder2/Extruder2Settings.tsx [hunk 11]
```diff
@@ -0,0 +1,31 @@
...
+    rotationState,
+  } = useExtruder2();
+  return (
+    <Page>
+      <ControlCard className="bg-red" title="Inverter Settings">
+        <Label label="Rotation Direction">
+          <SelectionGroupBoolean
+            value={rotationState}
+            optionTrue={{ children: "Backwards" }}
+            optionFalse={{ children: "Forwards" }}
```
Comment (1cedsoda) [inline electron/src/machines/extruder/extruder2/Extruder2Settings.tsx]: "Forward"

File: control-core/src/converters/motor_converter.rs [hunk 12]
```diff
@@ -0,0 +1,9 @@
+pub struct MotorConverter {}
+impl MotorConverter {
```
Comment (1cedsoda) [inline control-core/src/converters/motor_converter.rs]: The name does not fit the function.
Based on the functionality this converter is for an inverter not a motor.
Please make the Misubishi inverter functions take frequency as an input.

Put the conversion logic from screw speed to frequency into the controller of the screw speed.

If you want make some part of that code reusable you could create a `GearBox` structa that converts the 1:34 transmission.

File: electron/src/machines/types.ts [hunk 13]
```diff
@@ -175,6 +175,100 @@ export const winder2: MachinePreset = {
...
+        {
+          vendor_id: 2,
+          product_id: 0x44c2c52,
+          revision: 0x120000,
+        },
+      ],
+    },
+    {
+      role: 1,
+      role_label: "2X Digital Input",
```
Comment (1cedsoda) [inline electron/src/machines/types.ts]: Just "Digital Input"

File: electron/src/machines/types.ts [hunk 14]
```diff
@@ -175,6 +175,100 @@ export const winder2: MachinePreset = {
...
+        {
+          vendor_id: 2,
+          product_id: 65679442,
+          revision: 1179648,
+        },
+      ],
+    },
+    {
+      role: 2,
+      role_label: "1X Serial Interface For Inverter",
```
Comment (1cedsoda) [inline electron/src/machines/types.ts]: Just "Inverter Interface"

File: electron/src/machines/types.ts [hunk 15]
```diff
@@ -175,6 +175,100 @@ export const winder2: MachinePreset = {
...
+        {
+          vendor_id: 2,
+          product_id: 131346514,
+          revision: 1179648,
+        },
+      ],
+    },
+    {
+      role: 4,
+      role_label: "1x Analog Input 4-20mA",
```
Comment (1cedsoda) [inline electron/src/machines/types.ts]: Just "Pressure Sensor"

File: electron/src/machines/types.ts [hunk 16]
```diff
@@ -175,6 +175,100 @@ export const winder2: MachinePreset = {
...
+        {
+          vendor_id: 2,
+          product_id: 394604626,
+          revision: 0x160000,
+        },
+      ],
+    },
+    {
+      role: 3,
+      role_label: "4X Digital Out",
```
Comment (1cedsoda) [inline electron/src/machines/types.ts]: Just "Heating Elements"

File: electron/src/machines/types.ts [hunk 17]
```diff
@@ -175,6 +175,100 @@ export const winder2: MachinePreset = {
...
+        {
+          vendor_id: 2,
+          product_id: 197996626,
+          revision: 1310720,
+        },
+      ],
+    },
+    {
+      role: 5,
+      role_label: "4x Temperature",
```
Comment (1cedsoda) [inline electron/src/machines/types.ts]: Just "Thermometers"

File: electron/src/setup/DeviceEepromDialog.tsx [hunk 18]
```diff
@@ -76,6 +76,12 @@ export function DeviceEepromDialog({ device }: Props) {
   );
 }
 
+/*
+
+
+
+*/
+
```
Comment (1cedsoda) [inline electron/src/setup/DeviceEepromDialog.tsx]: remove this addition

File: electron/src/setup/DeviceEepromDialog.tsx [hunk 19]
```diff
@@ -97,6 +103,9 @@ export function DeviceEeepromDialogContent({ device, setOpen }: ContentProps) {
   });
   const values = useFormValues(form);
 
+  console.log(device);
+  console.log(device["device_identification"]["Ethercat"]);
+
```
Comment (1cedsoda) [inline electron/src/setup/DeviceEepromDialog.tsx]: remove this logging here

File: ethercat-hal/src/devices/el1002.rs [hunk 20]
```diff
@@ -0,0 +1,105 @@
+use super::{NewEthercatDevice, SubDeviceIdentityTuple};
+use crate::devices::EthercatDeviceProcessing;
+use crate::helpers::ethercrab_types::EthercrabSubDevicePreoperational;
+use crate::io::digital_input::{DigitalInputDevice, DigitalInputInput, DigitalInputState};
+use crate::pdo::{PredefinedPdoAssignment, TxPdo, basic::BoolPdoObject};
+use ethercat_hal_derive::{EthercatDevice, TxPdo};
+/// EL1002 8-channel digital input device
```
Comment (1cedsoda) [inline ethercat-hal/src/devices/el1002.rs]: empty line here

File: ethercat-hal/src/devices/el1002.rs [hunk 21]
```diff
@@ -0,0 +1,105 @@
...
+///
+/// 24V DC, 3ms filter
+#[derive(Clone, EthercatDevice)]
+pub struct EL1002 {
+    pub txpdo: EL1002TxPdo,
+}
```
Comment (1cedsoda) [inline ethercat-hal/src/devices/el1002.rs]: Please correct the description

File: ethercat-hal/src/devices/el2004.rs [hunk 22]
```diff
@@ -0,0 +1,97 @@
+use super::{EthercatDeviceProcessing, NewEthercatDevice, SubDeviceIdentityTuple};
+use crate::helpers::ethercrab_types::EthercrabSubDevicePreoperational;
+use crate::io::digital_output::{DigitalOutputDevice, DigitalOutputOutput, DigitalOutputState};
+use crate::pdo::{RxPdo, basic::BoolPdoObject};
+use ethercat_hal_derive::{EthercatDevice, RxPdo};
+/// EL2004 4-channel digital output device
```
Comment (1cedsoda) [inline ethercat-hal/src/devices/el2004.rs:6]: empty line here

File: ethercat-hal/src/devices/mod.rs [hunk 23]
```diff
@@ -15,6 +18,7 @@ pub mod el6021;
 pub mod el7031;
 pub mod el7031_0030;
 pub mod el7041_0052;
+
```
Comment (1cedsoda) [inline ethercat-hal/src/devices/mod.rs]: remove empty lines between `pub` so cargo fmt can format them

File: server/src/machines/extruder1/act.rs [hunk 24]
```diff
@@ -0,0 +1,74 @@
...
+                self.temperature_controller_back.update_pid(now_ts);
+                self.temperature_controller_nozzle.update_pid(now_ts);
+            }
+
+            let now = Instant::now();
+            if now.duration_since(self.last_measurement_emit) > Duration::from_millis(16) {
+                // channel 1
+                self.emit_heating(
+                    self.temperature_controller_back.heating.clone(),
+                    super::HeatingType::Back,
```
Comment (1cedsoda) [inline server/src/machines/extruder1/act.rs:27]: why do we need to give an enum and a heating? I think one is sufficient.

File: server/src/machines/extruder1/act.rs [hunk 25]
```diff
@@ -0,0 +1,74 @@
...
+                self.emit_rpm();
+
+                if self.mode == ExtruderV2Mode::Extrude && self.uses_rpm == false {
+                    self.pressure_motor_controller.target_pressure = self.target_bar as f64;
+                    let res = self
+                        .pressure_motor_controller
+                        .update(self.bar as f64, now_ts);
+                    let rpm = MotorConverter::hz_to_rpm(res as f32);
+                    self.inverter.set_running_rpm_target(rpm);
+                }
```
Comment (1cedsoda) [inline server/src/machines/extruder1/act.rs]: Whi is this inside the 60 fps event emitting block?

Please also don't but the fucking code here make a function for it like "sync_screw" or smthing.

File: server/src/machines/extruder1/act.rs [hunk 26]
```diff
@@ -0,0 +1,74 @@
...
+            self.set_bar();
+
+            if self.mode == ExtruderV2Mode::Standby {
+                self.turn_heating_off();
+            } else if self.mode == ExtruderV2Mode::Heat || self.mode == ExtruderV2Mode::Extrude {
+                self.temperature_controller_front.update_pid(now_ts);
+                self.temperature_controller_middle.update_pid(now_ts);
+                self.temperature_controller_back.update_pid(now_ts);
+                self.temperature_controller_nozzle.update_pid(now_ts);
+            }
```
Comment (1cedsoda) [inline server/src/machines/extruder1/act.rs]: Please put his code into it's own function somewhere else like `update_heating` or something.

File: server/src/machines/extruder1/api.rs [hunk 27]
```diff
@@ -0,0 +1,331 @@
...
+#[derive(Serialize, Debug, Clone)]
+pub struct RotationStateEvent {
+    pub forward: bool,
+}
+
+impl RotationStateEvent {
+    pub fn build(&self) -> Event<Self> {
+        Event::new("RotationStateEvent", self.clone())
+    }
+}
```
Comment (1cedsoda) [inline server/src/machines/extruder1/api.rs:59]: Pleas name this "ScrewStateEvent". Also other things that are directly related to the screw. Not "motor speed" but "screw speed"

File: server/src/machines/extruder1/api.rs [hunk 28]
```diff
@@ -0,0 +1,331 @@
...
+pub struct RpmStateEvent {
+    pub rpm: f32,
+    pub target_rpm: f32,
+}
+
+impl RpmStateEvent {
+    pub fn build(&self) -> Event<Self> {
+        Event::new("RpmStateEvent", self.clone())
+    }
+}
```
Comment (1cedsoda) [inline server/src/machines/extruder1/api.rs]: Merge this with `ScrewStateEvent`

File: server/src/machines/extruder1/api.rs [hunk 29]
```diff
@@ -0,0 +1,331 @@
...
+    SetRunningFrequency(f32),
+    SetEepromFrequency(f32),
+    SetMinimumFrequency(f32),
+    SetMaximumFrequency(f32),
+
+    ///Get
+    GetRunningFrequency(),
+    GetEepromFrequency(),
+    GetMaximumFrequency(),
+    GetMinimumFrequency(),
```
Comment (1cedsoda) [inline server/src/machines/extruder1/api.rs]: Get Requests are not Mutations please make an event for this. This is a no go

File: server/src/machines/extruder1/api.rs [hunk 30]
```diff
@@ -0,0 +1,331 @@
...
+
+#[derive(Deserialize, Serialize)]
+enum Mutation {
+    /// INVERTER
+    /// Frequency Control
+    /// Set
+    SetRunningFrequency(f32),
+    SetEepromFrequency(f32),
+    SetMinimumFrequency(f32),
+    SetMaximumFrequency(f32),
```
Comment (1cedsoda) [inline server/src/machines/extruder1/api.rs]: Why are these even here? Are they even UI related?

We just need one `ScrewSetDirection` and one `ScrewSetDirection`.

Remove `SetRunningFrequency`, `SetEepromFrequency `, `SetMinimumFrequency `, `SetMaximumFrequency `, `StopMotor`, `SetRotation`

We need fucking simple API interfaces or we will drown in interface complexity.

File: server/src/machines/extruder1/api.rs [hunk 31]
```diff
@@ -0,0 +1,331 @@
...
+    /// Inverter Control
+    SetOperationMode(u8),
+    WriteParameter(u16, u16),
+    ReadParameter(u16),
+
+    // Clears
+    ClearAllParameters(),
+    ClearParameter(),
+    ClearNonCommunicationParameter(),
+    ClearNonCommunicationParameters(),
```
Comment (1cedsoda) [inline server/src/machines/extruder1/api.rs]: Remove. Seems to me that you are putting control login in the frontend wtf.

File: server/src/machines/extruder1/api.rs [hunk 32]
```diff
@@ -0,0 +1,331 @@
...
+    SetHeatingFront(Heating),
+    SetHeatingBack(Heating),
+    SetHeatingMiddle(Heating),
+    SetHeatingNozzle(Heating),
+
+    SetFrontHeatingTemperature(f32),
+    SetBackHeatingTemperature(f32),
+    SetMiddleHeatingTemperature(f32),
+    SetNozzleHeatingTemperature(f32),
+}
```
Comment (1cedsoda) [inline server/src/machines/extruder1/api.rs]: Rename all Mutations to the naming schma used in the winder also. The naming schema goes as this:

1. Part of the machine that is controlled
2. Type of Operation like `Set`
3. What to `Set` specifially.

I know its a bit counterintuitive at first but think of the first part as like a resource. with a function `heating.set_target_front()` (`HeatingSetTargetFront`), `motor.set_speed()` (`MotorSetSpeed`)....

File: server/src/machines/extruder1/api.rs [hunk 33]
```diff
@@ -0,0 +1,331 @@
...
+            Mutation::GetMaximumFrequency() => todo!(),
+            Mutation::GetMinimumFrequency() => todo!(),
+            Mutation::StopMotor() => todo!(),
+            Mutation::SetOperationMode(_) => todo!(),
+            Mutation::WriteParameter(_, _) => todo!(),
+            Mutation::ReadParameter(_) => todo!(),
+            Mutation::ClearAllParameters() => todo!(),
+            Mutation::ClearParameter() => todo!(),
+            Mutation::ClearNonCommunicationParameter() => todo!(),
+            Mutation::ClearNonCommunicationParameters() => todo!(),
```
Comment (1cedsoda) [inline server/src/machines/extruder1/api.rs]: What this gobbely gook?

File: server/src/machines/extruder1/mod.rs [hunk 34]
```diff
@@ -0,0 +1,333 @@
...
+    uses_rpm: bool,
+    bar: f32,
+    target_rpm: f32,
+    target_bar: f32,
+    temperature_controller_front: TemperatureController,
+    temperature_controller_middle: TemperatureController,
+    temperature_controller_back: TemperatureController,
+    temperature_controller_nozzle: TemperatureController,
+    pressure_motor_controller: PressureController,
+}
```
Comment (1cedsoda) [inline server/src/machines/extruder1/mod.rs]: Why is `bar`, `target_rpm`, `target_bar` just lying around. Wrap them in a controller.

And not `PressureController`.... Make a `ScrewSpeedController` that handles all the targets and regulation mode.

File: server/src/machines/extruder1/mod.rs [hunk 35]
```diff
@@ -0,0 +1,333 @@
...
+            return;
+        }
+
+        match mode {
+            ExtruderV2Mode::Standby => self.switch_to_standby(),
+            ExtruderV2Mode::Heat => self.switch_to_heat(),
+            ExtruderV2Mode::Extrude => self.switch_to_extrude(),
+        }
+    }
+}
```
Comment (1cedsoda) [inline server/src/machines/extruder1/mod.rs]: Please put motor control functions into the `ScrewSpeedController`.

File: server/src/machines/extruder1/mod.rs [hunk 36]
```diff
@@ -0,0 +1,333 @@
...
+    }
+
+    fn emit_rotation_state(&mut self) {
+        let event = api::RotationStateEvent {
+            forward: self.inverter.forward_rotation.clone(),
+        }
+        .build();
+        self.namespace
+            .emit_cached(ExtruderV2Events::RotationStateEvent(event))
+    }
```
Comment (1cedsoda) [inline server/src/machines/extruder1/mod.rs]: put this to the other `impl` block for motor/ screw stuff

File: server/src/machines/extruder1/mod.rs [hunk 37]
```diff
@@ -0,0 +1,333 @@
...
+    fn emit_bar(&mut self) {
+        let event = api::PressureStateEvent {
+            bar: self.bar,
+            target_bar: self.target_bar,
+        }
+        .build();
+        self.namespace
+            .emit_cached(ExtruderV2Events::PressureStateEvent(event));
+    }
+}
```
Comment (1cedsoda) [inline server/src/machines/extruder1/mod.rs]: Put this to the other screw speed control `impl` block

File: server/src/machines/extruder1/pressure_controller.rs [hunk 38]
```diff
@@ -0,0 +1,38 @@
...
+        let freq = self.pid.update(error, now).clamp(MIN_FREQ, MAX_FREQ);
+        self.last_update = now;
+        freq
+    }
+
+    pub fn reset(&mut self) {
+        self.pid.reset();
+        self.last_update = Instant::now();
+    }
+}
```
Comment (1cedsoda) [inline server/src/machines/extruder1/pressure_controller.rs]: Rename to `ScrewSpeedController` and put all the logic here for constant or pressure driven control.

Look at some of the controllers inside the Winder V2 code like `SpoolSpeedController`

File: server/src/machines/extruder1/temperature_controller.rs [hunk 39]
```diff
@@ -0,0 +1,79 @@
...
+        }
+
+        // Compare duty cycle to elapsed time
+        let on_time = PWM_PERIOD.mul_f64(duty);
+
+        // Relay is ON if within duty cycle window
+        let on = elapsed < on_time;
+        self.relais.set(on);
+        self.heating.heating = on;
+    }
```
Comment (1cedsoda) [inline server/src/machines/extruder1/temperature_controller.rs]: Just one `update` function

File: server/src/machines/mod.rs [hunk 40]
```diff
@@ -1,7 +1,9 @@
 pub mod dre;
+pub mod extruder1;
 pub mod registry;
 pub mod winder2;
 
 pub const VENDOR_QITECH: u16 = 0x0001;
 pub const MACHINE_WINDER_V1: u16 = 0x0002;
+pub const MACHINE_EXTRUDER_V1: u16 = 0x0003;
```
Comment (1cedsoda) [inline server/src/machines/mod.rs]: Take a look at the root `README.md` and see that `3` is reserved for Extruder V1 so use `4`.

**Review by 1cedsoda — CHANGES_REQUESTED** [review]
My Review:
- Rust technically good 👍
- Some smaller naming fixes 🏷️
- Simplify API ☎️
- Some resorting where code belongs around the control mechanisms 💔

**Comment by 1cedsoda** [comment]
Sure that #98 is solved???

**Comment by 1cedsoda** [comment]
Also #193  is also not included in here I think, please remove it from the fix list

File: electron/src/setup/DeviceEepromDialog.tsx [hunk 41]
```diff
@@ -97,6 +103,9 @@ export function DeviceEeepromDialogContent({ device, setOpen }: ContentProps) {
   });
   const values = useFormValues(form);
 
+  console.log(device);
+  console.log(device["device_identification"]["Ethercat"]);
```
[the remark this answers is not in the document]
Comment (kraemr) [reply electron/src/setup/DeviceEepromDialog.tsx]: f8fdcbcf391bd3a6115f2ee785a6145abaadc934

File: electron/src/setup/DeviceEepromDialog.tsx (hunk 18 above)
[the remark this answers is not in the document]
Comment (kraemr) [reply electron/src/setup/DeviceEepromDialog.tsx]: e3e3839dbc66ed60ca00bf10e966e4001972a634

File: control-core/src/actors/digital_output_blinker.rs (hunk 1 above)
Comment (kraemr) [reply control-core/src/actors/digital_output_blinker.rs]: 9a140d803cf3fa63f328c3e6f8b9901534ce8981

File: control-core/src/actors/mitsubishi_inverter_rs485/init.rs (hunk 2 above)
Comment (kraemr) [reply control-core/src/actors/mitsubishi_inverter_rs485/init.rs]: 3539193f4650bba641e5c15ee53ea8a8a067581e

File: control-core/src/actors/mitsubishi_inverter_rs485/mod.rs (hunk 3 above)
Comment (kraemr) [reply control-core/src/actors/mitsubishi_inverter_rs485/mod.rs]: e6b99dbb513e9bd88920b639898ef36050de3074

File: control-core/src/actors/mitsubishi_inverter_rs485/mod.rs (hunk 4 above)
Comment (kraemr) [reply control-core/src/actors/mitsubishi_inverter_rs485/mod.rs]: ae93075dc82a22974844e98e9d4f009e288fc3b8

File: control-core/src/actors/mitsubishi_inverter_rs485/mod.rs (hunk 5 above)
Comment (kraemr) [reply control-core/src/actors/mitsubishi_inverter_rs485/mod.rs]: 691f03e9054785b387e6a8a3df782178e9199579

File: electron/src/machines/types.ts (hunk 13 above)
Comment (kraemr) [reply electron/src/machines/types.ts]: cd52a99fe5c925d2a15c4e12f7398dacd9ec7a73

File: electron/src/machines/types.ts (hunk 14 above)
Comment (kraemr) [reply electron/src/machines/types.ts]: cd52a99fe5c925d2a15c4e12f7398dacd9ec7a73

File: electron/src/machines/types.ts (hunk 15 above)
Comment (kraemr) [reply electron/src/machines/types.ts]: cd52a99fe5c925d2a15c4e12f7398dacd9ec7a73

File: electron/src/machines/types.ts (hunk 16 above)
Comment (kraemr) [reply electron/src/machines/types.ts]: cd52a99fe5c925d2a15c4e12f7398dacd9ec7a73

File: electron/src/machines/types.ts (hunk 17 above)
Comment (kraemr) [reply electron/src/machines/types.ts]: cd52a99fe5c925d2a15c4e12f7398dacd9ec7a73

File: ethercat-hal/src/devices/el1002.rs (hunk 20 above)
Comment (kraemr) [reply ethercat-hal/src/devices/el1002.rs]: 27959f041179a5037af8c37f6f32a724707d9650

File: ethercat-hal/src/devices/el1002.rs (hunk 21 above)
Comment (kraemr) [reply ethercat-hal/src/devices/el1002.rs]: 27959f041179a5037af8c37f6f32a724707d9650

File: ethercat-hal/src/devices/el2004.rs (hunk 22 above)
Comment (kraemr) [reply ethercat-hal/src/devices/el2004.rs:6]: 029edb2e540eb2850df524fe8d2add8454b33deb

File: ethercat-hal/src/devices/mod.rs (hunk 23 above)
Comment (kraemr) [reply ethercat-hal/src/devices/mod.rs]: 1d28abe664e9107743ea051051dca81afdcd435b

File: server/src/machines/mod.rs (hunk 40 above)
Comment (kraemr) [reply server/src/machines/mod.rs]: a0667f6bc7cda2ce6316093d91733bcf2d821cf0

File: server/src/machines/extruder1/temperature_controller.rs (hunk 39 above)
Comment (kraemr) [reply server/src/machines/extruder1/temperature_controller.rs]: 7caad4bb32653e4b541890e157de24945849a302

File: server/src/machines/extruder1/pressure_controller.rs (hunk 38 above)
Comment (kraemr) [reply server/src/machines/extruder1/pressure_controller.rs]: 00af80f53159a30014084e17edba4c95d1aa12dd

File: server/src/machines/extruder1/api.rs (hunk 33 above)
Comment (kraemr) [reply server/src/machines/extruder1/api.rs]: 4b952f55abfb07843c188c9b1c22387165383604

Comment (kraemr) [reply server/src/machines/extruder1/api.rs]: removed the unused mutations

File: server/src/machines/extruder1/mod.rs (hunk 35 above)
Comment (kraemr) [reply server/src/machines/extruder1/mod.rs]: https://github.com/qitechgmbh/control/commit/00af80f53159a30014084e17edba4c95d1aa12dd

File: server/src/machines/extruder1/mod.rs (hunk 34 above)
Comment (kraemr) [reply server/src/machines/extruder1/mod.rs]: https://github.com/qitechgmbh/control/commit/00af80f53159a30014084e17edba4c95d1aa12dd

File: server/src/machines/extruder1/api.rs (hunk 30 above)
Comment (kraemr) [reply server/src/machines/extruder1/api.rs]: https://github.com/qitechgmbh/control/commit/4b952f55abfb07843c188c9b1c22387165383604

File: server/src/machines/extruder1/api.rs (hunk 29 above)
Comment (kraemr) [reply server/src/machines/extruder1/api.rs]: https://github.com/qitechgmbh/control/commit/4b952f55abfb07843c188c9b1c22387165383604

File: server/src/machines/extruder1/act.rs (hunk 25 above)
Comment (kraemr) [reply server/src/machines/extruder1/act.rs]: https://github.com/qitechgmbh/control/commit/00af80f53159a30014084e17edba4c95d1aa12dd

File: server/src/machines/extruder1/api.rs (hunk 31 above)
Comment (kraemr) [reply server/src/machines/extruder1/api.rs]: https://github.com/qitechgmbh/control/commit/4b952f55abfb07843c188c9b1c22387165383604

File: electron/src/machines/extruder/extruder2/Extruder2Settings.tsx (hunk 11 above)
Comment (kraemr) [reply electron/src/machines/extruder/extruder2/Extruder2Settings.tsx]: 13610f6612a8098a28577a28349006887c665a0d

File: control-core/src/actors/temperature_input_getter.rs (hunk 7 above)
Comment (kraemr) [reply control-core/src/actors/temperature_input_getter.rs]: 4ad8abb88f3d73759eaf3a00a782c43da5c96efa

File: control-core/src/converters/motor_converter.rs (hunk 12 above)
Comment (kraemr) [reply control-core/src/converters/motor_converter.rs]: added transmission calculation 45038fc9c3d6bd788b16ce370ca14442b29154d3

File: server/src/machines/extruder1/api.rs (hunk 27 above)
Comment (kraemr) [reply server/src/machines/extruder1/api.rs:59]: e8d9c231dc81ede0726c3a1486c8190923a27eee

File: server/src/machines/extruder1/api.rs (hunk 32 above)
Comment (kraemr) [reply server/src/machines/extruder1/api.rs]: 22ec270561b83d4f19c78a258a6d6ca5b225f9a3

File: control-core/src/actors/mitsubishi_inverter_rs485/mod.rs [hunk 42]
```diff
@@ -188,14 +312,18 @@ impl MitsubishiInverterRS485Actor {
             state: State::Uninitialized,
             request_queue: VecDeque::new(),
             response_queue: VecDeque::new(),
+            forward_rotation: true,
+            next_response_type: ResponseType::ReadMotorFrequency,
+            last_request_type: RequestType::OperationCommand,
             last_message_size: 0,
             baudrate: None,
             encoding: None,
+            frequency: Frequency::new::<hertz>(0.0),
```
Comment (1cedsoda) [inline control-core/src/actors/mitsubishi_inverter_rs485/mod.rs]: use `Frequency::ZERO`

File: control-core/src/uom_extensions/rpm.rs [hunk 43]
```diff
@@ -0,0 +1,7 @@
+unit! {
+    system: uom::si;
+    quantity: uom::si::rpm;
+
+    @revolution_per_minute_per_second: 0.104_719_755_119_659_77; "rev/min/s", "revolutions per minute per second",
+        "revolutions per minute per second";
+}
```
Comment (1cedsoda) [inline control-core/src/uom_extensions/rpm.rs]: dublicate of `angular_aceleration.rs`

File: electron/src/machines/extruder/HeatingZone.tsx [hunk 44]
```diff
@@ -2,47 +2,69 @@ import { ControlCard } from "@/control/ControlCard";
 import { EditValue } from "@/control/EditValue";
 import { Label } from "@/control/Label";
 import { roundToDecimals } from "@/lib/decimal";
+
```
Comment (1cedsoda) [inline electron/src/machines/extruder/HeatingZone.tsx]: remove empty line

File: control-core/src/uom_extensions/acceleration.rs [hunk 45]
```diff
@@ -4,4 +4,5 @@ unit! {
 
     @meter_per_minute_per_second: 0.016_666_666_666_666_67; "m/min/s", "meters per minute per second",
         "meters per minute per second";
+
```
Comment (1cedsoda) [inline control-core/src/uom_extensions/acceleration.rs]: remove useless change

File: electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx [hunk 46]
```diff
@@ -0,0 +1,146 @@
...
+    SetHeatingBackTemp,
+    SetHeatingMiddleTemp,
+    InverterSetRegulation,
+    uses_rpm,
+    barTs,
+    rpmTs,
+    targetBar,
+    targetRpm,
+    InverterSetTargetPressure,
+    InverterSetTargetRpm,
```
Comment (1cedsoda) [inline electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx]: Please look at the difference to the winder

- capitalization (functions and vars do not have a capital starting letter just components and types...)
- naming order
- ...

```rust

  const {
    laserpointer,
    setLaserpointer,
    laserpointerIsLoading,
    laserpointerIsDisabled,
    tensionArmAngle,
    tensionArmAngleZero,
    tensionArmState,
    tensionArmStateIsLoading,
    tensionArmStateIsDisabled,
    spoolRpm,
    mode,
    setMode,
    modeIsLoading,
    modeIsDisabled,
    pullerState,
    pullerSpeed,
    pullerSetRegulationMode,
    pullerSetTargetSpeed,
    pullerStateIsLoading,
    pullerStateIsDisabled,
    traversePosition,
    traverseState,
    traverseSetLimitInner,
    traverseSetLimitOuter,
    traverseGotoLimitInner,
    traverseGotoLimitOuter,
    traverseGotoHome,
    traverseStateIsLoading,
    traverseStateIsDisabled,
    modeState,
  } = useWinder2();
  ```

File: server/Cargo.toml [hunk 47]
```diff
@@ -21,7 +21,7 @@ tower-http = { version = "0.6.2", features = ["cors", "trace", "fs"] }
 axum = { version = "0.8.4", features = ["macros"] }
 
 # utility
-uom = { version = "0.36.0", features = ["f64", "serde"] }
+uom = { version = "0.36.0",default-features = false, features = ["f64"]}
```
Comment (1cedsoda) [inline server/Cargo.toml]: `, ` missing space

File: server/src/machines/extruder1/screw_speed_controller.rs [hunk 48]
```diff
@@ -0,0 +1,166 @@
...
+    uses_rpm: bool,
+    forward_rotation: bool,
+}
+
+impl ScrewSpeedController {
+    pub fn new(
+        inverter: MitsubishiInverterRS485Actor,
+        kp: f64,
+        ki: f64,
+        kd: f64,
```
Comment (1cedsoda) [inline server/src/machines/extruder1/screw_speed_controller.rs]: Define the PID factos inside the controller not outside, since this controller is not reused

File: server/src/machines/extruder1/screw_speed_controller.rs [hunk 49]
```diff
@@ -0,0 +1,166 @@
...
+            false => MitsubishiControlRequests::StartForwardRotation.into(),
+        };
+        self.inverter.add_request(req);
+    }
+
+    pub fn set_target_pressure(&mut self, target_pressure: Pressure) {
+        self.target_pressure = target_pressure;
+    }
+
+    pub fn set_target_screw_rpm(&mut self, target_rpm: f64) {
```
Comment (1cedsoda) [inline server/src/machines/extruder1/screw_speed_controller.rs]: `uom`

File: server/src/machines/extruder1/screw_speed_controller.rs [hunk 50]
```diff
@@ -0,0 +1,166 @@
...
+        // Use uom here and perhaps clamp it
+        let target_rpm = AngularVelocity::new::<revolution_per_minute>(target_rpm);
+        let target_motor_rpm = target_rpm * TRANSMISSION_RATIO as f64;
```
Comment (1cedsoda) [inline server/src/machines/extruder1/screw_speed_controller.rs]: please make a struct `TransmissionConverter` instead of using a const value

File: server/src/machines/extruder1/temperature_controller.rs [hunk 51]
```diff
@@ -0,0 +1,103 @@
...
+            let duty = control.clamp(0.0, 1.0);
+            let elapsed = now.duration_since(self.window_start);
+
+            // Restart window if needed
+            if elapsed >= PWM_PERIOD {
+                self.window_start = now;
+            }
+
+            // Compare duty cycle to elapsed time
+            let on_time = PWM_PERIOD.mul_f64(duty);
```
Comment (1cedsoda) [inline server/src/machines/extruder1/temperature_controller.rs]: please make PWM period not a const.

You could also make a struct `PwmDigitalOutput` so we could reuse this logic

File: control-core/src/actors/mitsubishi_inverter_rs485/mod.rs (hunk 42 above)
Comment (kraemr) [reply control-core/src/actors/mitsubishi_inverter_rs485/mod.rs]: 926c8f7f4dbc510bf797249bb8d8a3a9cd9ab7aa

File: control-core/src/uom_extensions/rpm.rs (hunk 43 above)
Comment (kraemr) [reply control-core/src/uom_extensions/rpm.rs]: dublicate is removed 50ac55c2c17a736048d036639daf3d204b5879df

File: electron/src/machines/extruder/HeatingZone.tsx (hunk 44 above)
Comment (kraemr) [reply electron/src/machines/extruder/HeatingZone.tsx]: 7cca56e20ac5de65575ef394ffec4127f3def54e

File: control-core/src/uom_extensions/acceleration.rs (hunk 45 above)
Comment (kraemr) [reply control-core/src/uom_extensions/acceleration.rs]: 58c1880488e5a8378b384188c5b0257bd11d2969

File: server/src/machines/extruder1/screw_speed_controller.rs (hunk 48 above)
Comment (kraemr) [reply server/src/machines/extruder1/screw_speed_controller.rs]: 2e538fdad5230654262abbfa3156e531435fe13b

File: server/src/machines/extruder1/temperature_controller.rs (hunk 51 above)
Comment (kraemr) [reply server/src/machines/extruder1/temperature_controller.rs]: 18adf63937f4dd2e39af32ce63a4fa25c15c2a56

Comment (kraemr) [reply server/src/machines/extruder1/temperature_controller.rs]: 18adf63937f4dd2e39af32ce63a4fa25c15c2a56

File: server/src/machines/extruder1/screw_speed_controller.rs (hunk 49 above)
Comment (kraemr) [reply server/src/machines/extruder1/screw_speed_controller.rs]: 7aa3222efd6ac0874c9ccc053550c8bc7632dfaa

File: server/src/machines/extruder1/screw_speed_controller.rs (hunk 50 above)
Comment (kraemr) [reply server/src/machines/extruder1/screw_speed_controller.rs]: 125efe0e639df32f966d121ba5e1ae797b35b51d

File: electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx [hunk 52]
```diff
@@ -0,0 +1,146 @@
...
+    frontTemperature,
+    backHeatingState,
+    backTemperature,
+    middleHeatingState,
+    middleTemperature,
+    extruderSetMode,
+    heatingBackSetTemp,
+    heatingFrontSetTemp,
+    heatingNozzleSetTemp,
+    heatingMiddleSetTemp,
```
Comment (1cedsoda) [inline electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx]: `heatingSet...Temp`

File: electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx [hunk 53]
```diff
@@ -0,0 +1,146 @@
...
+    inverterSetRegulation,
+    inverterSetTargetPressure,
+    inverterSetTargetScrewRpm,
```
Comment (1cedsoda) [inline electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx]: still inverter???

**Review by 1cedsoda — CHANGES_REQUESTED** [review]

File: electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx (hunk 52 above)
Comment (kraemr) [reply electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx]: 36462865f6cdb0f54948742d7ee20f8e38f3f254

File: electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx (hunk 53 above)
Comment (kraemr) [reply electron/src/machines/extruder/extruder2/Extruder2ControlPage.tsx]: 36462865f6cdb0f54948742d7ee20f8e38f3f254
