### PR TITLE
377 inverter state machine and el6021 incorrectly handle requestresponses

### LINKED ISSUE #377: Inverter State Machine and EL6021 incorrectly handle request/responses
Due to incorrect state transitions requests and responses may be desynced from each other causing incorrect response handling.

### PR DESCRIPTION
**Pull request by kraemr**
fix #377

### CODE REVIEW

File: control-core/src/actors/mitsubishi_inverter_rs485/mod.rs [hunk 1]
```diff
@@ -432,7 +431,7 @@ impl MitsubishiInverterRS485Actor {
                 }
                 Err(_) => {
                     self.last_message_size = 22;
-                    self.state = State::WaitingForReceiveAccept;
+                    //                    self.state = State::WaitingForReceiveAccept;
```
Comment (1cedsoda) [inline control-core/src/actors/mitsubishi_inverter_rs485/mod.rs]: whitespace

File: control-core/src/actors/mitsubishi_inverter_rs485/mod.rs [hunk 2]
```diff
@@ -569,14 +568,16 @@ impl MitsubishiInverterRS485Actor {
         };
     }
 
-    fn handle_response(&mut self, resp: ModbusResponse) {
+    async fn handle_no_response(&mut self) {}
```
Comment (1cedsoda) [inline control-core/src/actors/mitsubishi_inverter_rs485/mod.rs]: remove this?

File: ethercat-hal/src/io/serial_interface.rs [hunk 3]
```diff
@@ -145,6 +177,8 @@ where
     fn get_serial_encoding(&self, port: PORTS) -> Option<SerialEncoding>;
     fn get_baudrate(&self, port: PORTS) -> Option<u32>;
     fn serial_interface_initialize(&mut self, port: PORTS) -> bool;
+    fn serial_interface_write_finished(&mut self, port: PORTS) -> bool;
+    fn serial_interface_read_finished(&mut self, port: PORTS) -> bool;
```
Comment (1cedsoda) [inline ethercat-hal/src/io/serial_interface.rs]: try to eliminiate these
