### PR TITLE
1187 aquapath fixes

### LINKED ISSUE #1070: Aquapath UI Left Right Problem
It is not clear by the name of the Reservoir(Reservoir 1, Reservoir 2) which of them is on the right Side or on the left Side. And it is confusing that the left reservoirs UI is displayed on the Right side of the Monitor and the right one displayed on the left side.

### LINKED ISSUE #1132: Improve aquapath backend code
The controller for the aquapath is a complete mess and we should rewrite it in a clean way.

### PR DESCRIPTION
**Pull request by JalleliAchraf**
- Aquapath backend: PID+PWM heating + warmup
- relay-safe switching (min on/off dwell)
- flow/pump interlock required for thermal actions
- cooling control upgraded to staged RPM ramp
- ambient calibration added (settings)
- Aquapath status UI cleaned: heating/cooling badges improved, low-value heater power display removed
- tolerances for cooling and heating and PID variables customizable via settings page

### CODE REVIEW

File: machines/src/aquapath1/mod.rs [hunk 1]
```diff
@@ -348,29 +434,124 @@ impl AquaPathV1 {
 }
 
 impl AquaPathV1 {
+    const PID_MIN: f64 = 0.0;
```
Comment (just-some-entity) [inline machines/src/aquapath1/mod.rs]: move constants up to have them grouped

File: machines/src/aquapath1/mod.rs [hunk 2]
```diff
@@ -102,6 +103,11 @@ impl AquaPathV1 {
         vendor: VENDOR_QITECH,
         machine: MACHINE_AQUAPATH_V1,
     };
+    pub const DEFAULT_HEATING_TOLERANCE_C: f64 = 0.4;
```
Comment (just-some-entity) [inline machines/src/aquapath1/mod.rs]: remove letter as unit and add a comment specifying the unit

File: machines/src/aquapath1/controller.rs [hunk 3]
```diff
@@ -5,17 +5,67 @@ use ethercat_hal::io::encoder_input::EncoderInput;
...
-use std::time::Instant;
+use std::time::{Duration, Instant};
 use units::AngularVelocity;
 use units::angular_velocity::revolution_per_minute;
 use units::f64::ThermodynamicTemperature;
 use units::thermodynamic_temperature::{degree_celsius, kelvin};
 use units::volume_rate::liter_per_minute;
-#[derive(Debug)]
+#[derive(Debug, Clone, Copy)]
+pub struct CoolingRampConfig {
```
Comment (just-some-entity) [inline machines/src/aquapath1/controller.rs:38]: use physical units instead of f64 values

**Comment by TheBest6337** [comment]
@JalleliAchraf please resolve the requested changes and rebase.

**Comment by JalleliAchraf** [comment]
Summary of changes : 
- very low flow automatically sets pump to off preventing illegal state where flow is 0 and pump is on which may cause unexpected behavior
- setting pump to off/on always resets the PID/PWM controller so that stale states don't affect the control anymore (preventing overshooting or weird behavior)
- PID parameter changes from setting also refresh PID/PWM 
- frontend notifications every time a PWM/PID reset occurs
- notifications when pump is forced off because of very low flow 

I tested and it behaves as expected so far 
@just-some-entity @TheBest6337  
Please conduct more tests before merging if possible

**Comment by just-some-entity** [comment]
When turning off the pumps the water temperature inside the heater rises significantly due to missing flow and has a risk of evaporating at high temperatures. When the heating element was recently turned on, the controller should wait a period for it to cool down before turning off the pumps. Additionally, heating should only turn on after target flow has been reached for a certain duration, not once it has been detected.

**Comment by just-some-entity** [comment]
And display the cooldown period of the pump in the ui

**Comment by just-some-entity** [comment]
And display the watt usage of the heater similar to how it is displayed in the extruder

File: machines/src/aquapath1/new.rs [hunk 4]
```diff
@@ -134,28 +136,12 @@ impl MachineNewTrait for AquaPathV1 {
...
 
             let back_controller = Controller::new(
-                0.10,
-                0.0,
-                0.015,
+                AquaPathV1::DEFAULT_PID_KP,
+                AquaPathV1::DEFAULT_PID_KI,
+                AquaPathV1::DEFAULT_PID_KD,
                 Temperature::default(),
                 ThermodynamicTemperature::new::<degree_celsius>(25.0),
```
Comment (just-some-entity) [inline machines/src/aquapath1/new.rs:146]: Define magic number

File: machines/src/aquapath1/new.rs [hunk 5]
```diff
@@ -167,6 +153,25 @@ impl MachineNewTrait for AquaPathV1 {
...
+                AquaPathV1::DEFAULT_PID_KI,
+                AquaPathV1::DEFAULT_PID_KD,
+                Temperature::default(),
+                ThermodynamicTemperature::new::<degree_celsius>(25.0),
+                ao1,
+                do4,
+                do2,
+                t1,
+                t2,
+                AngularVelocity::new::<revolution_per_minute>(100.0),
```
Comment (just-some-entity) [inline machines/src/aquapath1/new.rs:170]: Define magic number

File: machines/src/aquapath1/new.rs [hunk 6]
```diff
@@ -167,6 +153,25 @@ impl MachineNewTrait for AquaPathV1 {
...
                 enc2,
+                controller_config,
+            );
+
+            let front_controller = Controller::new(
+                AquaPathV1::DEFAULT_PID_KP,
+                AquaPathV1::DEFAULT_PID_KI,
+                AquaPathV1::DEFAULT_PID_KD,
+                Temperature::default(),
+                ThermodynamicTemperature::new::<degree_celsius>(25.0),
```
Comment (just-some-entity) [inline machines/src/aquapath1/new.rs:164]: Define magic number

File: machines/src/aquapath1/api.rs
Comment (just-some-entity) [inline machines/src/aquapath1/api.rs:16]: I would prefer if back and front could be abstracted behind a simple struct to reduce duplication and possible errors by forgetting to mirror a value of one of the sides

File: machines/src/aquapath1/new.rs [hunk 7]
```diff
@@ -178,6 +183,9 @@ impl MachineNewTrait for AquaPathV1 {
                     namespace: params.namespace.clone(),
                 },
                 mode: AquaPathV1Mode::Standby,
+                ambient_temperature_calibration: ThermodynamicTemperature::new::<degree_celsius>(
```
Comment (just-some-entity) [inline machines/src/aquapath1/new.rs:186]: Define magic number

**Comment by TheBest6337** [comment]
@JalleliAchraf please resolve the requested changes.

File: electron/src/machines/aquapath/aquapath1/aquapath1Namespace.ts [hunk 8]
```diff
@@ -82,6 +115,18 @@ export const liveValuesEventDataSchema = z.object({
   back_revolutions: z.number(),
   back_power: z.number(),
   front_power: z.number(),
+  front_heating: z.boolean().optional().default(false),
+  back_heating: z.boolean().optional().default(false),
+  front_cooling_mode: coolingModeSchema.nullable().optional().default(null),
```
Comment (Oshgnacknak) [inline electron/src/machines/aquapath/aquapath1/aquapath1Namespace.ts:120]: You don't need the `optional()` here

File: electron/src/machines/aquapath/aquapath1/aquapath1Namespace.ts [hunk 9]
```diff
@@ -127,11 +182,23 @@ export type Aquapath1NamespaceStore = {
...
+  combinedPower: TimeSeries;
 
   front_total_energy: TimeSeries;
   back_total_energy: TimeSeries;
-
-  // Target value history (for graph target lines)
+  totalEnergyKWh: TimeSeries;
+  front_heating: boolean;
+  back_heating: boolean;
+  front_cooling_mode: "Low" | "Ramp" | "Max" | null;
```
Comment (Oshgnacknak) [inline electron/src/machines/aquapath/aquapath1/aquapath1Namespace.ts:192]: pls use the cooling mode schema

File: machines/src/aquapath1/controller.rs [hunk 10]
```diff
@@ -1,21 +1,100 @@
...
+    Ramp,
+    Max,
+}
+
+#[derive(Debug, Clone, Copy)]
+pub struct CoolingRampConfig {
+    pub tolerance: ThermodynamicTemperature,
+    pub near_band: ThermodynamicTemperature,
+    pub full_band: ThermodynamicTemperature,
+    pub min_rpm: f64,
```
Comment (Oshgnacknak) [inline machines/src/aquapath1/controller.rs:42]: the is a unit for rpm
