### PR TITLE
425 fix terminal component issues v2

### LINKED ISSUE #425: Fix `Terminal` Component Issues
- When using a terminal component multiple times (like multiple updates) the lines are replicated n times
- Use list virtualization to improve performance for long logs

### PR DESCRIPTION
**Pull request by kraemr**
fix #425

### CODE REVIEW

File: electron/src/helpers/update_helpers.ts [hunk 1]
```diff
@@ -1,16 +1,28 @@
...
+    }
+
+    currentLogListener = onLog;
+    window.update.onLog(currentLogListener);
+
     window.update.execute(source);
+
     window.update.onEnd((params) => {
-      window.update.onLog(() => {});
+      window.update.onLog(() => {}); // remove listener
```
Comment (Oshgnacknak) [inline electron/src/helpers/update_helpers.ts:23]: Optimally, there would be a method called `removeOnLogListener` or something like that. But thats just the icing on the cake.

File: nixos/modules/qitech.nix [hunk 2]
```diff
@@ -107,7 +107,7 @@ serviceConfig = {
       
       environment = {
         RUST_BACKTRACE = "full";
-        RUST_LOG = "info";
+        RUST_LOG = "debug";
```
Comment (Oshgnacknak) [inline nixos/modules/qitech.nix]: I assume we don't want this on master

**Review by Oshgnacknak — CHANGES_REQUESTED** [review]

File: nixos/modules/qitech.nix (hunk 2 above)
Comment (kraemr) [reply nixos/modules/qitech.nix]: We had this on master a long time as a default but yeah id say lets stick with info
